### ISSUE TITLE
Module changes text selectable

### ISSUE THREAD

**Issue by thatlonelybugbear** [theripper93/libChangelogs#4]
Don't know if something like that is doable, but a use case would be selecting some part of the text in the changelog to copy and paste in the macro editor of foundry for example.

![image](https://user-images.githubusercontent.com/7237090/142005725-f8e93b7f-c6d8-4bb6-ac90-6fd2158a4c0f.png)

eg. Select the part `items.data.flags.midi-qol.noProvokeReaction` to copy and paste it :D

**Comment by theripper93** [comment]
That is kind of an issue because of how the markdown is compiled, but you can use a neat  trick, if you type `document.designMode = "on"` in the console (or in a macro) you will be able to select any text, you can set it to off to disable
