### ISSUE TITLE
Message on startup not necessary

### ISSUE THREAD

**Issue by DarKDinDoN** [theripper93/libChangelogs#5]
Hello,

When there are no new changes or conflicts, the GM still gets a foundry "blue" notification on startup.
Not sure if that's necessary :)

![image](https://user-images.githubusercontent.com/1687854/146150195-89443b23-52dd-4eb3-b32c-3c81edc3ff6a.png)

**Comment by theripper93** [comment]
ah, that's fair, it was meant to only appear when you open changelogs with the button, whops

**Comment by theripper93** [comment]
should be fixed
