### ISSUE TITLE
Possible conflict between Variant Encumbrance and DF Quality of Life

### ISSUE THREAD

**Issue by GabrielOsvair** [theripper93/libChangelogs#7]
The Changelog and Conflicts module reports incompatibility between the Variant Encumbrance and DF Quality of Life. It makes several updates that this happens and the warning does not go away. Any settings I disable between them also do not remove the warning.

Check more details here: https://github.com/VanirDev/VariantEncumbrance/issues/61

**Comment by theripper93** [comment]
You are always gonna see the conflicts not even sure what you are reporting here
